import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import DaMenu from "@/components/layout/daMenu";
import "./globals.css";

const courierPrime = Courier_Prime({
  weight: "400",
  variable: "--font-courier-prime",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sickness Unto Death",
  description: "Generated by Jaylen Luc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${courierPrime.variable} bg-[#d2b48c] overflow-hidden antialiased`}
      >
        <div className="fixed top-0 left-0 z-50 w-64 h-64">
          <DaMenu />
        </div>
        <div className="mt-32 md:mt-0 relative pt-0">
          {children}
        </div>
      </body>
    </html>
  );
}
