export const emotionalThemes: string[] = [
  "Joy",
  "Grief",
  "Anxiety",
  "Rage",
  "Nostalgia",
  "Shame",
  "Guilt",
  "Euphoria",
  "Emptiness",
  "Longing",
  "Awe",
  "Dread",
  "Hope",
  "Despair",
  "Melancholy",
  "Serenity",
  "The Shadow",
  "The Self",
  "The Anima",
  "The Animus",
  "The Persona",
  "Individuation",
  "Archetype",
  "Synchronicity",
  "Collective Unconscious",
  "Transformation",
  "Repression",
  "Projection",
  "Inner Child",
  "Integration",
  "Death-Rebirth",
  "Angst",
  "Authenticity",
  "Despair of the Self",
  "Leap of Faith",
  "Subjectivity",
  "The Absurd",
  "Alienation",
  "Freedom",
  "Responsibility",
  "The Ethical",
  "The Aesthetic",
  "The Religious",
  "Faith",
  "Sickness Unto Death",
  "Becoming",
  "Love",
  "Betrayal",
  "Isolation",
  "Belonging",
  "Conflict",
  "Connection",
  "Power",
  "Intimacy",
  "Abandonment",
  "Trust",
  "Mirror",
  "Labyrinth",
  "Threshold",
  "Descent",
  "Flight",
  "Mask",
  "Fire",
  "Water",
  "Forest",
  "Void",
  "Light",
  "Darkness"
];