export const emotionalThemes: string[] = [
  // Emotions & Internal States
  "Joy",
  "Grief",
  "Anxiety",
  "Rage",
  "Nostalgia",
  "Shame",
  "Guilt",
  "Euphoria",
  "Emptiness",
  "Longing",
  "Awe",
  "Dread",
  "Hope",
  "Despair",
  "Melancholy",
  "Serenity",

  // Jungian Themes & Archetypes
  "The Shadow",
  "The Self",
  "The Anima",
  "The Animus",
  "The Persona",
  "Individuation",
  "Archetype",
  "Synchronicity",
  "Collective Unconscious",
  "Transformation",
  "Repression",
  "Projection",
  "Inner Child",
  "Integration",
  "Death-Rebirth",

  // Kierkegaardian & Existential Themes
  "Angst",
  "Authenticity",
  "Despair of the Self",
  "Leap of Faith",
  "Subjectivity",
  "The Absurd",
  "Alienation",
  "Freedom",
  "Responsibility",
  "The Ethical",
  "The Aesthetic",
  "The Religious",
  "Faith",
  "Sickness Unto Death",
  "Becoming",

  // Relational & Social Experience
  "Love",
  "Betrayal",
  "Isolation",
  "Belonging",
  "Conflict",
  "Connection",
  "Power",
  "Intimacy",
  "Abandonment",
  "Trust",

  // Symbolic & Dreamlike Themes
  "Mirror",
  "Labyrinth",
  "Threshold",
  "Descent",
  "Flight",
  "Mask",
  "Fire",
  "Water",
  "Forest",
  "Void",
  "Light",
  "Darkness"
];